# Algebra liniowa z biblioteką Numpy


W tym laboratorium będziesz miał okazję zapamiętać kilka podstawowych pojęć dotyczących algebry liniowej i sposobu jej wykorzystania w Pythonie.

Numpy jest jedną z najczęściej używanych bibliotek w Pythonie do manipulacji wektorami. Dodaje ona do Pythona zestaw funkcji, które pozwalają nam operować na dużych, wielowymiarowych wektorach z zaledwie kilkoma liniami kodu. Zapomnij więc o pisaniu pętli zagnieżdżonych do dodawania wektorów! Z NumPy, to jest tak proste jak dodawanie liczb.

Zaimportujmy bibliotekę `numpy` i przypiszmy do niej alias `np`. Będziemy stosować się do tej konwencji w prawie każdym notebooku tego kursu, a zobaczycie to również w wielu zasobach spoza tego kursu.

In [1]:
import numpy as np  # najbardziej znana biblioteka data scientistów

## Definiowanie list i wektorów NumPy

In [2]:
alist = [1, 2, 3, 4, 5]   # Definicja listy w pythonie, wygląda jak wektor
narray = np.array([1, 2, 3, 4]) # Definicja macierzy numpy

Zwróć uwagę na różnicę pomiędzy listą w Pythonie, a wektorem NumPy

In [3]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


## Działania algebraiczne - różnice między wektorem NumPy a listą w Pythonie

Jednym z częstych błędów początkujących jest mieszanie pojęć wektora NumPy i listy w Pythonie. Wystarczy spojrzeć na następny przykład, w którym dodajemy dwa obiekty dwóch wymienionych typów. Zauważ, że operator '+' na wektorach NumPy dokonuje dodawania elementów, podczas gdy ta sama operacja na listach Pythona skutkuje konkatenację listy. Bądź ostrożny podczas kodowania. Wiedza na ten temat może oszczędzić wiele bólu głowy.

In [4]:
print(narray + narray)
print(alist + alist)

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Podobnie wygląda operator mnożenia`*`. W pierwszym przypadku skalujemy wektor, a w drugim łączymy trzy razy tę samą listę.

In [5]:
print(narray * 3)
print(alist * 3)

[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Bądź świadomy tej różnicy, ponieważ w ramach tej samej funkcji mogą pojawić się oba rodzaje zmiennych. 
Wektory NumPy są przeznaczone do operacji numerycznych i macierzy, natomiast listy służą do bardziej ogólnych celów.

## Macierz lub wektor wektorów

W algebrze liniowej, macierz jest strukturą złożoną z n rzędów po m kolumn. Oznacza to, że każdy wiersz musi mieć taką samą liczbę kolumn. Z NumPy mamy dwa sposoby na stworzenie macierzy:
* Tworzenie wektora wektorów przy użyciu `np.array` (zalecane). 
* Tworzenie macierzy przy użyciu `np.matrix` (wciąż dostępna, ale może być wkrótce usunięta).

Wektory NumPy lub listy mogą być użyte do inicjalizacji macierzy, ale wynikowa macierz będzie składać się tylko z wektorów NumPy.

In [6]:
npmatrix1 = np.array([narray, narray, narray]) # Macierz tworzona jako wektor wektorów
npmatrix2 = np.array([alist, alist, alist]) # Macierz tworzona z listy
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray]) # Macierz tworzona z listy i wektora

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


Jednak podczas definiowania macierzy należy się upewnić, że wszystkie wiersze zawierają taką samą liczbę elementów. W przeciwnym razie, operacje algebry liniowej mogą prowadzić do nieoczekiwanych wyników.

Przeanalizuj poniższe dwa przykłady:

In [7]:
# Przykład 1:

okmatrix = np.array([[1, 2], [3, 4]]) # Macierz 2x2
print(okmatrix) # Wypisujemy macierz
print(okmatrix * 2) # wypisujemy macierz po skalowaniu

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [8]:
# Przykład 2:

badmatrix = np.array([[1, 2], [3, 4], [5, 6, 7]]) # Definiujemy macierz, trzeci rząd zawiera 3 elementy
print(badmatrix) # Wypisujemy niepełną macierz
print(badmatrix * 2) # Spodziewamy się przeskalowanej macierzy

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


## Skalowanie i transponowanie macierzy

Teraz, gdy już wiesz jak zbudować poprawne wektory i macierze NumPy, zobaczmy jak łatwo jest z nimi operować w Pythonie używając zwykłych operatorów algebraicznych jak + i -. 

Operacje mogą być wykonywane między wektorami i macierzami lub między wektorami i skalarami.

In [24]:
# Mnożymy macierz razy 2 i dodajemy jeden
result = okmatrix * 2 + 1 # Dla każdego elementu macierzy
print(result)

[[3 5]
 [7 9]]


In [25]:
# dodajemy dwie kompatybilne macierze
result1 = okmatrix + okmatrix
print(result1)

# Odejmujemy dwie kompatybilne macierze
result2 = okmatrix - okmatrix
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


Operator produktu `*` w przypadku stosowania na wektorach lub macierzach wskazuje na oddzielne mnożenie każdego elementu.
Nie należy go mylić z tzw. działaniem "dot".

In [26]:
result = okmatrix * okmatrix # Mnożymy każdy element przez siebie
print(result)

[[ 1  4]
 [ 9 16]]


## Transponowanie macierzy

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimension is n by m, the resulting transposed matrix will be m by n.

**T** denotes the transpose operations with NumPy matrices.

In [27]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]]) # Define a 3x2 matrix
print('Original matrix 3 x 2')
print(matrix3x2)
print('Transposed matrix 2 x 3')
print(matrix3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


However, note that the transpose operation does not affect 1D arrays.

In [28]:
nparray = np.array([1, 2, 3, 4]) # Definiujemy wektor
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


perhaps in this case you wanted to do:

In [30]:
nparray = np.array([[1, 2, 3, 4]]) # Definiujemy macierz 1 x 4. Zwróć uwagę na podwójne nawiasy kwadratowe
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


## Get the norm of a nparray or matrix

In linear algebra, the norm of an n-dimensional vector $\vec a$   is defined as:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2}$$

Calculating the norm of vector or even of a matrix is a general operation when dealing with data. Numpy has a set of functions for linear algebra in the subpackage **linalg**, including the **norm** function. Let us see how to get the norm a given array or matrix:

In [31]:
nparray1 = np.array([1, 2, 3, 4]) # Define an array
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array([[1, 2], [3, 4]]) # Define a 2 x 2 matrix. Note the 2 level of square brackets
norm2 = np.linalg.norm(nparray2) 

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


Note that without any other parameter, the norm function treats the matrix as being just an array of numbers.
However, it is possible to get the norm by rows or by columns. The **axis** parameter controls the form of the operation: 
* **axis=0** means get the norm of each column
* **axis=1** means get the norm of each row. 

In [32]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

normByCols = np.linalg.norm(nparray2, axis=0) # Get the norm for each column. Returns 2 elements
normByRows = np.linalg.norm(nparray2, axis=1) # get the norm for each row. Returns 3 elements

print(normByCols)
print(normByRows)

[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


However, there are more ways to get the norm of a matrix in Python.
For that, let us see all the different ways of defining the dot product between 2 arrays.

## The dot product between arrays: All the flavors

The dot product or scalar product or inner product between two vectors $\vec a$ and $\vec a$ of the same size is defined as:
$$\vec a \cdot \vec b = \sum_{i=1}^{n} a_i b_i$$

The dot product takes two vectors and returns a single number.

In [33]:
nparray1 = np.array([0, 1, 2, 3]) # Define an array
nparray2 = np.array([4, 5, 6, 7]) # Define an array

flavor1 = np.dot(nparray1, nparray2) # Recommended way
print(flavor1)

flavor2 = np.sum(nparray1 * nparray2) # Ok way
print(flavor2)

flavor3 = nparray1 @ nparray2         # Geeks way
print(flavor3)

# As you never should do:             # Noobs way
flavor4 = 0
for a, b in zip(nparray1, nparray2):
    flavor4 += a * b
    
print(flavor4)

38
38
38
38


**We strongly recommend using np.dot, since it is the only method that accepts arrays and lists without problems**

In [34]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4])) # Dot product on nparrays
norm2 = np.dot([1, 2], [3, 4]) # Dot product on python lists

print(norm1, '=', norm2 )

11 = 11


Finally, note that the norm is the square root of the dot product of the vector with itself. That gives many options to write that function:

$$ norm(\vec a) = ||\vec a|| = \sqrt {\sum_{i=1}^{n} a_i ^ 2} = \sqrt {a \cdot a}$$


## Sums by rows or columns

Another general operation performed on matrices is the sum by rows or columns.
Just as we did for the function norm, the **axis** parameter controls the form of the operation:
* **axis=0** means to sum the elements of each column together. 
* **axis=1** means to sum the elements of each row together.

In [35]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. 

sumByCols = np.sum(nparray2, axis=0) # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(nparray2, axis=1) # get the sum for each row. Returns 3 elements

print('Sum by columns: ')
print(sumByCols)
print('Sum by rows:')
print(sumByRows)

Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


## Get the mean by rows or columns

As with the sums, one can get the **mean** by rows or columns using the **axis** parameter. Just remember that the mean is the sum of the elements divided by the length of the vector
$$ mean(\vec a) = \frac {{\sum_{i=1}^{n} a_i }}{n}$$

In [36]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]]) # Define a 3 x 2 matrix. Chosen to be a matrix with 0 mean

mean = np.mean(nparray2) # Get the mean for the whole matrix
meanByCols = np.mean(nparray2, axis=0) # Get the mean for each column. Returns 2 elements
meanByRows = np.mean(nparray2, axis=1) # get the mean for each row. Returns 3 elements

print('Matrix mean: ')
print(mean)
print('Mean by columns: ')
print(meanByCols)
print('Mean by rows:')
print(meanByRows)

Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


## Center the columns of a matrix

Centering the attributes of a data matrix is another essential preprocessing step. Centering a matrix means to remove the column mean to each element inside the column. The sum by columns of a centered matrix is always 0.

With NumPy, this process is as simple as this:

In [37]:
nparray2 = np.array([[1, 1], [2, 2], [3, 3]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2 - np.mean(nparray2, axis=0) # Remove the mean for each column

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by column')
print(nparrayCentered.mean(axis=0))

Original matrix
[[1 1]
 [2 2]
 [3 3]]
Centered by columns matrix
[[-1. -1.]
 [ 0.  0.]
 [ 1.  1.]]
New mean by column
[0. 0.]


**Warning:** This process does not apply for row centering. In such cases, consider transposing the matrix, centering by columns, and then transpose back the result. 

See the example below:

In [38]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

nparrayCentered = nparray2.T - np.mean(nparray2, axis=1) # Remove the mean for each row
nparrayCentered = nparrayCentered.T # Transpose back the result

print('Original matrix')
print(nparray2)
print('Centered by columns matrix')
print(nparrayCentered)

print('New mean by rows')
print(nparrayCentered.mean(axis=1))

Original matrix
[[1 3]
 [2 4]
 [3 5]]
Centered by columns matrix
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]
New mean by rows
[0. 0. 0.]


Note that some operations can be performed using static functions like `np.sum()` or `np.mean()`, or by using the inner functions of the array

In [39]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]]) # Define a 3 x 2 matrix. 

mean1 = np.mean(nparray2) # Static way
mean2 = nparray2.mean()   # Dinamic way

print(mean1, ' == ', mean2)

3.0  ==  3.0


Even if they are equivalent, we recommend the use of the static way always.

**Congratulations! You have successfully reviewed vector and matrix operations with Numpy!**